version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/node:8.11
        environment:
          SERVER_WORKERS: 2
          SESSION_SECRET: abcdef123
          SSO_DOMAIN: localhost
          SSO_CLIENT: abc123
          SSO_SECRET: def567
          SSO_PATH_AUTH: /a/path/
          SSO_PATH_TOKEN: /a/token/
          SSO_PATH_INTROSPECT: /a/introspect/
          SSO_REDIRECT_URI: localhost
          SSO_BYPASS: true
      - image: redis:3
    steps:
      - checkout
      - restore_cache:
          key: node-modules-{{ arch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - run: npm test
      - run: npm run coverage
      - run: npm run build:dist
      - save_cache:
          key: node-modules-{{ arch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
            - "dist/node_modules"
      - run:
          command: npm start
          background: true
      - run: npm run test:health
