version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/node:8.11
        environment:
          SERVER_WORKERS: 2
    steps:
      - checkout
      - restore_cache:
          key: node-modules-{{ arch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - run: npm test
      - run: npm run build:dist
      - save_cache:
          key: node-modules-{{ arch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
            - "dist/node_modules"
      - run:
          command: npm start
          background: true
      - run: npm run test:health
